# https://github.com/marketplace/actions/sticky-pull-request-comment
# according to the documentation above we might need to adapt the messages with headers.

name: Run Lint Test and Formatting Scrips

on:
  pull_request:
    branches:
        - main

jobs:
    runChecks:
        runs-on: ubuntu-latest
        permissions:
            contents: write
            pull-requests: write
        #strategy??? Maybe we need strategy.

        steps:
            - uses: actions/checkout@v4

            - name: run checks
              uses: actions/setup-node@v4
              # Might be good to test using different node versions
              
            - run: npm ci


            - name: run tests
              if: '!cancelled()'
              run: |
                npm run test | tee test-output.txt


            - name: run lint
              if: '!cancelled()'
              run: |
                npm run lint | tee lint-output.txt


            - name: run format
              if: '!cancelled()'
              run: |
                npm run format | tee format-output.txt


      

            - name: Aggregate results
              run: |
                set -e
      
                # Ensure all files exist
                touch test-output.txt lint-output.txt format-output.txt
      
                TEST_RESULTS=$(cat test-output.txt)
                LINT_RESULTS=$(cat lint-output.txt)
                FORMAT_RESULTS=$(cat format-output.txt)
      
                TEST_SUMMARY=$(echo "$TEST_RESULTS" | grep -E 'Tests.*' || echo "Tests passed without errors VERY SUS")
                LINT_SUMMARY=$(echo "$LINT_RESULTS" | grep -E 'lint.*' || echo "Linting passed without errors VERY SUS")
                FORMAT_SUMMARY=$(echo "$FORMAT_RESULTS" | grep -E 'format.*' || echo "Formatting passed without errors VERY SUS")
      
                echo "## CI Results" > comment-body.txt
                echo "### Lint Results" >> comment-body.txt
                echo "\`\`\`" >> comment-body.txt
                echo "$LINT_SUMMARY" >> comment-body.txt
                echo "\`\`\`" >> comment-body.txt
      
                echo "### Test Results" >> comment-body.txt
                echo "\`\`\`" >> comment-body.txt
                echo "$TEST_SUMMARY" >> comment-body.txt
                echo "\`\`\`" >> comment-body.txt
      
                echo "### Format Results" >> comment-body.txt
                echo "\`\`\`" >> comment-body.txt
                echo "$FORMAT_SUMMARY" >> comment-body.txt
                echo "\`\`\`" >> comment-body.txt

                COMMENT_BODY=$(cat comment-body.txt)
                echo "COMMENT_BODY<<EOF" >> $GITHUB_ENV
                echo "$COMMENT_BODY" >> $GITHUB_ENV
                echo "EOF" >> $GITHUB_ENV
            
            - name: Post results comment
              uses: marocchino/sticky-pull-request-comment@v2
              with:
                header: 'CI Results'
                message: |
                  ${{ env.COMMENT_BODY }}